import json,html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
offers=json.loads((root/'content/offers.json').read_text())
e=html.escape
invite='https://pc.moppy.jp/entry/invite.php?invite=Jh7He170&openExternalBrowser=1'
source='https://pc.moppy.jp/shopping/detail.php?site_id=1854'
date='2026-09-05'
header='<header class="header"><a class="logo" href="../index.html">P<span class="point-o">O</span>I DAYS</a><nav aria-label="メインナビ"><a href="../index.html#ranking">案件ランキング</a><a href="../index.html#diagnosis">診断</a></nav><a class="small-button" href="'+e(invite)+'" target="_blank" rel="sponsored noopener">無料ではじめる</a></header>'
for o in offers:
    rows=[('獲得条件',o['condition']),('必要な費用',o['cost']),('予定反映の目安',o['pending']),('確定反映の目安',o['confirmed'])]
    steps=''.join(f'<li><span>STEP {i}</span><p>{e(s)}</p></li>' for i,s in enumerate(o['steps'],1))
    pitfalls=''.join('<li>'+e(s)+'</li>' for s in o['pitfalls'])
    related=''.join(f'<a href="{x["id"]}.html">{e(x["name"])}のやり方 →</a>' for x in offers if x['id']!=o['id'])
    extra=f'<li><a href="{e(o["extraSource"])}" target="_blank" rel="noopener">U-NEXT公式：無料体験の料金・解約</a></li>' if o.get('extraSource') else ''
    page=f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(o['name'])}のやり方・獲得条件｜POI DAYS</title><meta name="description" content="{e(o['name'])}のモッピー経由の進め方。条件、費用、反映時期、対象外になる注意点を整理。"><link rel="stylesheet" href="../style.css"></head><body>{header}<main class="guide-main container narrow"><p class="breadcrumb"><a href="../index.html">ホーム</a> / <a href="../index.html#ranking">案件一覧</a> / {e(o['name'])}</p><p class="eyebrow">MOPPY GUIDE · PR</p><h1>{e(o['name'])}<br>やり方と、気をつけたいこと。</h1><p class="source">情報確認日：2026年9月5日（日本時間）｜公式情報を整理したガイド。実利用の体験談ではありません。</p><div class="guide-summary"><p>{e(o['category'])} ／ 確認時の還元</p><strong>{e(o['reward'])}</strong><p>向いている人：{e(o['fit'])}</p><p class="result-note">{e(o['caution'])}</p><p class="micro">この金額は確認時点の記録です。現在の掲載・還元・対象条件は公式で再確認してください。</p><a class="button primary" href="{e(o['url'])}" rel="noopener" target="_blank">モッピーで最新条件を見る →</a><p class="micro">モッピー未登録なら、<a href="{e(invite)}" rel="sponsored noopener" target="_blank">招待リンクから登録</a>した後、この案件に戻ってください。招待コード：Jh7He170</p></div><nav class="guide-toc" aria-label="目次"><a href="#conditions">条件・費用</a><a href="#howto">やり方</a><a href="#pitfalls">注意点</a><a href="#questions">よくある質問</a></nav><section id="conditions"><h2>最初に、条件を確認。</h2><dl class="condition-table">{''.join('<div><dt>'+e(k)+'</dt><dd>'+e(v)+'</dd></div>' for k,v in rows)}</dl><p class="micro">反映時期は目安で、承認や付与日を保証しません。対象外条件の全文は公式広告にあります。</p></section><section id="howto"><h2>申し込みから確認まで。</h2><ol class="guide-steps">{steps}</ol></section><section id="pitfalls"><h2>取り逃さないために。</h2><ul class="guide-notes">{pitfalls}</ul><p>ポイントについての問い合わせは、広告ごとの受付可否・期限を確認してモッピーへ。申込情報は承認まで保管しましょう。</p></section><section id="questions"><h2>よくある質問</h2><details open><summary>{e(o['faq'])}</summary><p>{e(o['answer'])}</p></details><details><summary>このガイドの金額が公式と違ったら？</summary><p>公式の申込時点の条件を優先してください。このページは確認日付きの記録で、毎日の自動更新はまだ行っていません。</p></details></section><section><h2>確認してから、はじめよう。</h2><a class="button primary" href="{e(o['url'])}" rel="noopener" target="_blank">最新条件を見て案件へ進む →</a><p><a class="text-link" href="../index.html#planner">費用も含めて試算する →</a></p><p class="source">情報源</p><ul class="source"><li><a href="{e(o['url'])}" target="_blank" rel="noopener">モッピー公式：{e(o['name'])}の条件</a></li>{extra}</ul></section><section><h2>ほかの案件のやり方</h2><div class="related-guides">{related}</div></section></main><footer><div class="container"><a class="logo" href="../index.html">POI DAYS</a><p>当サイトは紹介報酬を受け取る場合があります。モッピー公式サイトではありません。</p></div></footer></body></html>'''
    (root/'dist/guides'/f'{o["id"]}.html').write_text(page)
def card(o):
    badge=f'公式総合 {o["rank"]}位' if o['rank'] else '使い方ガイド'
    return f'''<article class="offer-card"><span class="offer-rank">{badge}</span><p class="eyebrow">{e(o['category'])}</p><h3>{e(o['name'])}</h3><strong class="offer-reward">{e(o['reward'])}</strong><p>{e(o['condition'])}</p><p class="offer-cost">{e(o['cost'])}</p><a class="button outline" href="guides/{o['id']}.html">やり方・注意点を見る →</a></article>'''
block=f'''<section class="section ranking" id="ranking"><div class="container"><p class="eyebrow">MOPPY RANKING</p><h2>モッピー案件ランキング</h2><p class="section-lead">2026年9月5日確認の、公式総合トップ3。<br>気になる案件は、やり方までチェック。</p><p class="ranking-date">確認日：2026年9月5日（日本時間）・自動更新ではありません</p><div class="offer-grid">{''.join(card(o) for o in offers if o['rank'])}</div><details class="ranking-method"><summary>このランキングの見方・情報源</summary><p>モッピー公式ページ内「ジャンル別ランキング・総合」の確認時点の上位3件を、表示順のまま掲載しています。POI DAYS独自の人気順位や還元額順ではありません。公式側の集計期間・算出方法は確認できていません。</p><p>ポイント数は詳細ページの条件も確認しています。楽天銀行は一覧の通常ポイントと詳細のチャレンジボーナスを分けて表示。異なるサービスや条件の金額を単純に比較しないでください。</p><a href="{source}" target="_blank" rel="noopener">出典：モッピー公式ページ内の総合ランキング</a></details><h2 class="more-guides-heading">日常で使える案件も。</h2><div class="offer-grid extra-offers">{''.join(card(o) for o in offers if not o['rank'])}</div><p class="micro">こちらの2件は総合トップ3とは別の編集部選定です。掲載順は順位ではありません。掲載金額には招待による入会特典を含めていません。</p></div></section>'''
p=root/'dist/index.html';s=p.read_text();start='<!-- OFFERS START -->';end='<!-- OFFERS END -->'
if start in s:s=s[:s.index(start)]+start+block+end+s[s.index(end)+len(end):]
else:s=s.replace('<section id="about"',start+block+end+'<section id="about"',1)
s=s.replace('<a href="#ways">貯める</a>','<a href="#ranking">案件ランキング</a>')
p.write_text(s)
